import './globals.css'
import Header from '../components/header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
<html lang="en" style={{ height: "100%" }}>
  <body style={{ height: "100%" }}>
    <Header />
    <div style={{ height: "90%" }}>
      {children}
    </div>
  </body>
</html>
  )
}